import { PresentationConfig } from "@/types/presentation";

export const presentationConfig: PresentationConfig = {
  title: "NOAA Fisheries Modernization & Ecosystem Insights",
  shortTitle: "NOAA Fisheries Template",
  subtitle: "A Clean, Mobile-First Presentation Template for Interactive Data & Strategy Decks",
  author: "NOAA Fisheries Technology & Data Branch",
  version: "1.0.0",
  lastUpdated: "2026",
  slides: [
    {
      id: "slide-1",
      type: "title",
      title: "NOAA Fisheries Presentation Template",
      subtitle: "Mobile-first, minimalist React & Next.js deck engineered for rapid presentation authoring.",
      category: "TEMPLATE SHOWCASE",
      author: "Applications Delivery Branch",
      authorRole: "Data & Systems Architecture",
      date: "August 2026",
      tags: ["Mobile First", "NOAA Design System", "Next.js", "Framer Motion"],
      logoPath: "/logos/fisheries.png",
      notes: "Title cover slide showcasing fisheries.png logo and Coral accent line.",
    },
    {
      id: "slide-2",
      type: "split",
      title: "Mobile-First Design Architecture",
      subtitle: "Fluid responsiveness ensuring every slide renders cleanly on smartphones, tablets, and desktop displays.",
      category: "LAYOUT PRIMITIVES",
      bullets: [
        "100% Light Mode UI featuring clean contrast and soft slate backdrops.",
        "Touch swipe navigation built-in for seamless smartphone slide transitions.",
        "Auto-stacking columns: 2-column layouts smoothly collapse to 1-column on mobile viewports.",
        "Strict typography hierarchy using Inter font weights without heavy bolds.",
      ],
      mediaType: "card",
      mediaCardTitle: "Ecosystem Key Performance Highlights",
      mediaCardItems: [
        { label: "Target Touch Area", value: "≥ 44px Tap Targets" },
        { label: "Primary Brand Color", value: "NOAA Blue #003087" },
        { label: "High-Contrast Accent", value: "Coral Orange #FF6B4A" },
        { label: "Ecosystem Accent", value: "Seagrass Green #00A88F" },
      ],
      mediaCaption: "Responsive split layout automatically adapting to all viewport sizes.",
    },
    {
      id: "slide-3",
      type: "metrics",
      title: "Impact Metrics & Ecosystem Data",
      subtitle: "High-visibility KPI cards designed for quick scanning with animated entrance counters.",
      category: "DATA VISUALIZATION",
      metrics: [
        {
          id: "m-1",
          value: "478+",
          label: "Managed Fish Stocks",
          description: "Sustainable marine fishery management programs tracked nationwide.",
          trend: "+12% Efficiency",
          badgeColor: "seagrass",
        },
        {
          id: "m-2",
          value: "99.9%",
          label: "Uptime & Availability",
          description: "Real-time data feeds accessible across regional science centers.",
          trend: "Optimal",
          badgeColor: "noaa",
        },
        {
          id: "m-3",
          value: "100%",
          label: "Mobile Responsiveness",
          description: "Optimized for mobile field inspection & executive viewing.",
          trend: "Verified",
          badgeColor: "coral",
        },
      ],
      summaryNote: "Data figures rendered with Sky Gold and Seagrass indicators for maximum contrast.",
    },
    {
      id: "slide-4",
      type: "featureGrid",
      title: "Reusable Design System Components",
      subtitle: "Modular UI building blocks ready to be extended by future presenters and AI coding agents.",
      category: "COMPONENT CATALOG",
      features: [
        {
          id: "f-1",
          title: "Global Navigation Dropdown",
          description: "Top navigation header with instant slide jumper and active reading progress bar.",
          iconName: "Menu",
          badge: "Top Nav",
          accentColor: "noaa",
        },
        {
          id: "f-2",
          title: "Touch & Key Controls",
          description: "Swipe gestures on smartphones, arrow key listeners, and fullscreen toggling.",
          iconName: "Smartphone",
          badge: "Mobile Jumper",
          accentColor: "coral",
        },
        {
          id: "f-3",
          title: "PRD & AI Skill Integration",
          description: "Built-in deck-spec/ directory and SKILL.md for autonomous coding agent slide generation.",
          iconName: "Bot",
          badge: "AI Powered",
          accentColor: "seagrass",
        },
      ],
    },
    {
      id: "slide-5",
      type: "quote",
      title: "Ecosystem Conservation Statement",
      subtitle: "Clean, high-impact presentation quote layout featuring refined Inter typography.",
      category: "EXECUTIVE STATEMENT",
      quote: "Science-based stewardship of our nation's living marine resources guarantees economic resilience, ocean biodiversity, and coastal community vitality for generations to come.",
      author: "NOAA Fisheries Leadership",
      authorTitle: "National Oceanic and Atmospheric Administration",
      organization: "U.S. Department of Commerce",
    },
    {
      id: "slide-6",
      type: "code",
      title: "Extending Slides via TypeScript & AI Skill",
      subtitle: "Simple type-safe presentation data model that AI coding agents can easily manipulate.",
      category: "DEVELOPER INTEGRATION",
      snippet: {
        language: "typescript",
        filename: "src/content/slides.ts",
        code: `export const slide: SlideData = {
  id: "slide-new",
  type: "metrics",
  title: "New Survey Results",
  category: "FIELD DATA",
  metrics: [
    { value: "4.8M", label: "Square Miles Monitored", badgeColor: "seagrass" }
  ]
};`,
      },
      explanationBullets: [
        "Type safety: Every slide component is backed by strict TypeScript interfaces.",
        "PRD Workflow: Agents draft PRESENTATION_PRD.md before updating src/content/slides.ts.",
        "Instant HMR: Next.js hot module reloading updates presentation view immediately during live edits.",
      ],
    },
  ],
};
